### ISSUE TITLE
host@user gives an error 

### ISSUE THREAD

**Issue by noobishply** [lyiriyah/nim-fetch#1]
Doing `nimble run` in the directory gives this error in the host@user section:
`/bin/sh: line 1: hostname: command not found@noobishply`
![image](https://user-images.githubusercontent.com/76582002/127151914-5fe6d81a-f2f7-4605-8a88-b8760b4935ce.png)

**Comment by lyiriyah** [comment]
I'll use the $HOSTNAME variable instead.
